language: minimal
services: docker
arch:
        - amd64
        - arm64
os: linux
dist: bionic
branches:
        only:
        - master
jobs:
    include:
        - stage: "Build"
        - script: .travis/run.sh --package foo/bar
        - script: .travis/run.sh --package foo/bar-bin --notests
