language: minimal
services: docker
arch:
        - amd64
        - arm64
os: linux
dist: focal
branches:
        only:
        - master

script: .travis/run.sh --package foo/bar
script: .travis/run.sh --package foo/bar-bin --notests
