language: minimal
services: docker
arch:
        - amd64
        - arm64
os: linux
dist: focal
branches:
        only:
        - master
#Register the packages you want to track here, in the form ${CATEGORY}/${PN}
#Doing this via envs may seem weird, but it makes maintenance and workarounds easier and avoids code duplication
env:
        - PACKAGE=foo/bar
        - PACKAGE=foo/bar-bin
script: .travis/run.sh
